### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by dtangster** [progress-engine/tarantool.ex#5]
Since I'm both new to Tarantool and Elixir, I had issues with using your client. Is it functional or am I using it wrong?

I notice that calls to query operations like SELECT, INSERT, etc requires 2 parameters: a socket connection, and a tuple. Where do we get the connection?

Are we supposed to run it like so:

{:ok, pid} = Tarantool.start_link()

and then use the pid in another call? I didn't quite understand how the macro code works. Please show a simple example usage for each operation.

**Comment by spscream** [comment]
@dtangster, yes, you should use it like following:

```
iex(1)> {:ok, t} = Tarantool.start_link
{:ok, #PID<0.129.0>}
iex(2)> Tarantool.Api.ping(t)
{:ok, %{0 => 0, 1 => 0, 5 => 56}, %{}}
iex(3)> Tarantool.Api.auth(t, %{password: "111222", username: "amalaev"})
{:ok, %{0 => 0, 1 => 1, 5 => 56}, %{}}
(search)`sele': Tarantool.Api.select(t, %{space_id: 280, limit: 100, key: [], index_id: nil, iterator: nil, offset: 100})
{:ok, %{0 => 0, 1 => 2, 5 => 56}, %{48 => []}}
```

but currently I'm waiting to merge my PR and example above is for my current branch. For current version of tarantool.ex you should use Tarantool.ping Tarantool.select calls.

This is very early version of driver and it has a very low level of api realized and documentation for it is on todo list.

**Comment by spscream** [comment]
So my pr is accepted, you could use an api from example above, it should work.

**Comment by dtangster** [comment]
Thanks!

Will this update get pushed on to hex soon? Or do I have to apply the patch manually?

**Comment by spscream** [comment]
Yes, it should be available from hex now

**Comment by spscream** [comment]
@dtangster I add some examples to README.md, hope it will help you

**Comment by spscream** [comment]
Closing this issue, we added some examples to README.md
